server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://34.64.146.13/library?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ezen-dana
    password: EzenDanaLibrary8090@@

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.format_sql: true

  servlet:
    multipart:
      enabled: true
      location: /path/to/your/upload/folder  # 업로드된 파일을 저장할 경로
      max-request-size: 10MB  # 한 번에 최대 업로드 가능 용량
      max-file-size: 5MB  # 하나의 파일 최대 크기

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: kang456dh0606@gmail.com 
    password: jquxmyvlvahrqqnz 
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
