server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://34.64.146.13/library?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ezen-dana
    password: EzenDanaLibrary8090@@
   
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.format_sql: true